### ISSUE TITLE
IntelliJ import settings do not match Eclipse ones.

### ISSUE THREAD

**Issue by burmanm** [hawkular/hawkular-build-tools#9]
In Eclipse there's:

```
#Organize Import Order
#Fri Jan 16 11:30:31 EST 2015
3=com
2=org
1=javax
0=java
```

However in the IntelliJ settings.jar:

``` xml
  <option name="IMPORT_LAYOUT_TABLE">
    <value>
      <emptyLine />
      <package name="java" withSubpackages="true" static="false" />
      <emptyLine />
      <package name="javax" withSubpackages="true" static="false" />
      <emptyLine />
      <package name="" withSubpackages="true" static="false" />
      <emptyLine />
      <package name="" withSubpackages="true" static="true" />
    </value>
  </option>
```

Having defined only com/org doesn't sound convincing, there's plenty of libraries which are not using either of those beginnings and all the imports should somehow have consistent layout (why not alphabetical for other than JDK's internal?)

**Comment by tsegismont** [comment]
Right, so 'org' and 'com' are missing in IDEA settings.

As for the order, that's just an agreed order, personally I don't care 
which one we peek provided everyone uses the same.

**Comment by ppalaga** [comment]
@burmanm I suppose, this was solved in between? Please re-open if necessary.
